version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
    - 15.0.0
  - dependency-name: next-pwa
    versions:
    - 5.1.4
    - 5.2.1
    - 5.2.14
    - 5.2.3
    - 5.2.5
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.21.0
  - dependency-name: styled-components
    versions:
    - 5.2.2
